import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const body = Roboto({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${body.className} flex justify-center p-12`}>{children}</body>
    </html>
  );
}
